blank_issues_enabled: false
contact_links:
  - name: "ðŸ’¡ Questions, Feedback & Feature Requests"
    url: https://github.com/dcpesses/code-whisperer/discussions/new?category=ideas
    about: Got an idea? Drop your suggestions here!
